apiVersion: v2
appVersion: v14.0.0
dependencies:
- alias: redis-cache
  condition: redis-cache.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- alias: redis-queue
  condition: redis-queue.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- alias: redis-socketio
  condition: redis-socketio.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 10.3.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.0.3
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: https://raw.githubusercontent.com/frappe/design/master/logos/logo-2018/erpnext-logo-blue.svg
name: erpnext
type: application
version: 5.0.2
